// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BasePointGenerator
{
    internal sealed partial class Vsix
    {
        public const string Id = "BasePointGenerator.1bda164c-2fba-43e6-91bb-424ac2a31dac";
        public const string Name = "BasePoint generator";
        public const string Description = @"Generate clean architecture structure with BasePoint framework";
        public const string Language = "en-US";
        public const string Version = "0.0.5";
        public const string Author = "Elias da Silva Rita";
        public const string Tags = "C#, CSharp,Clean architecture, DDD, OOP, Repository, Unit Tests, Dapper, Productivity, Scaffolding";
    }
}
